// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","id":"1"},"2":{"path":"/","id":"2"},"3":{"path":"/","redirect":"/dashboard","parentId":"2","id":"3"},"4":{"path":"/dashboard","parentId":"2","id":"4"},"5":{"path":"/user","parentId":"2","id":"5"},"6":{"path":"/product","parentId":"2","id":"6"},"7":{"path":"/category","parentId":"2","id":"7"},"8":{"path":"/order","parentId":"2","id":"8"},"9":{"path":"/marketing","parentId":"2","id":"9"},"10":{"path":"/coupon","parentId":"2","id":"10"},"11":{"path":"/delivery","parentId":"2","id":"11"},"12":{"path":"/statistics","parentId":"2","id":"12"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__login__index" */'@/pages/login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "layouts__BasicLayout" */'@/layouts/BasicLayout.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__dashboard__index" */'@/pages/dashboard/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__user__index" */'@/pages/user/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__product__index" */'@/pages/product/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__category__index" */'@/pages/category/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__order__index" */'@/pages/order/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__marketing__index" */'@/pages/marketing/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__coupon__index" */'@/pages/coupon/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__delivery__index" */'@/pages/delivery/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__statistics__index" */'@/pages/statistics/index.tsx')),
},
  };
}
